// Copyright (c) 2011 SameGoal LLC.
// All Rights Reserved.
// Author: Andy Hochhaus

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/js/javascript_package.proto

#ifndef PROTOBUF_protobuf_2fjs_2fjavascript_5fpackage_2eproto__INCLUDED  // NOLINT
#define PROTOBUF_protobuf_2fjs_2fjavascript_5fpackage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>  // NOLINT

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>  // NOLINT
#include <google/protobuf/repeated_field.h>  // NOLINT
#include <google/protobuf/extension_set.h>  // NOLINT
#include <google/protobuf/generated_message_reflection.h>  // NOLINT
#include "google/protobuf/descriptor.pb.h"  // NOLINT
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protobuf_2fjs_2fjavascript_5fpackage_2eproto();
void protobuf_AssignDesc_protobuf_2fjs_2fjavascript_5fpackage_2eproto();
void protobuf_ShutdownFile_protobuf_2fjs_2fjavascript_5fpackage_2eproto();


// ===================================================================


// ===================================================================

static const int kJavascriptPackageFieldNumber = 50000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,  // NOLINT
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  javascript_package;

// ===================================================================


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protobuf_2fjs_2fjavascript_5fpackage_2eproto__INCLUDED  // NOLINT
